[package]
name = "seq_align"
version = "0.1.0"
edition = "2021"
authors = ["Kacper Ozieblowski", "Rodrigue Tavernier"]

[lib]
name = "seq_align"
path = "src/lib.rs"

[dependencies]
simple-error = "0.1.9"

[[bench]]
name = "dist"
harness = false