[package]
name = "RuNA"
version = "0.1.0"
edition = "2021"
authors = ["Kacper Ozieblowski", "Rodrigue Tavernier"]

[lib]
name = "runa"
path = "src/lib.rs"

[dependencies]
chrono = "0.4.23" # for printing time in benchmarks
simple-error = "0.1.9"
# no-panic = "0.1.16" # ensure that some functions never panic

[[bench]]
name = "bench"
harness = false